language: cpp
sudo: false
compiler:
 - gcc

dist: bionic
os:
  - linux

env:
    - VERSION=8

cache:
  directories:
  - $HOME/OpenFOAM


addons:
  apt:
    update: true
    packages:
      - flexc++
      - lcov
      - libopenmpi-dev

before_install:
  - git clone  --depth 1 https://github.com/OpenFOAM/OpenFOAM-$VERSION.git  $HOME/OpenFOAM/OpenFOAM-$VERSION
  - ls  $HOME/OpenFOAM

install:
    - source $HOME/OpenFOAM/OpenFOAM-$VERSION/etc/bashrc
      # skip compilation of applications
    - sed -i "s/applications/#applications/" $WM_PROJECT_DIR/Allwmake
    - cd $WM_PROJECT_DIR/ && ./Allwmake

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
