name: Integration Tests

defaults:
 run:
  shell: bash -o pipefail -i {0}

run-name: Unit tests on ${{github.ref_name}}

env:
  BUILD_TYPE: Release

jobs:
    - uses: actions/checkout@v4

    - name: Get Ginkgo checkout version
      shell: bash
      run: |
        grep -A1 "set(GINKGO_CHECKOUT_VERSION" CMakeLists.txt|tail -n1|grep -o  "[0-9a-z\-]*" > GINKGO_CHECKOUT_VERSION
        export GINKGO_CHECKOUT_VERSION=$(cat GINKGO_CHECKOUT_VERSION)
        echo "GINKGO_CHECKOUT_VERSION=$GINKGO_CHECKOUT_VERSION" >> $GITHUB_ENV

    - name: Cache build folder
      uses: actions/cache@v3
      with:
        key: build-${{ matrix.OF.path }}-${{env.GINKGO_CHECKOUT_VERSION}}
        path: |
          ${{github.workspace}}/build

    - name: Test OGL
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ./unitTests/matrixConversion
